# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('old', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='old.Old')),
            ],
            options={
                'db_table': 'boarding_visits',
                'verbose_name': 'boarding visit',
                'verbose_name_plural': 'boarding visits',
            },
        ),
    ]
